services:
  - type: web
    name: stock-bot
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7844949436:AAGuSSKfIaxojLMCcoWT2gigrq7ofv06zyQ
